import "../styles/globals.css";
import { Kanit } from "next/font/google";

const inter = Kanit({ subsets: ["thai"], weight: ["400"] });

// export const metadata = {
//   title: "Thai Framer Center",
//   description: "Generated by create next app",
// };

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
